# Generated by Django 4.2.1 on 2023-06-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_dastavka_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dastavka',
            name='location',
            field=models.CharField(choices=[('Andijon shahar', 'Andijon shahar'), ('bogishamol', 'bogishamol'), ('yangi bozor', 'yangi bozor'), ('eski shahar', 'eski shahar'), ('bobur shoh kocha', 'bobur shox kocha')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dastavka',
            name='title',
            field=models.CharField(choices=[('BURGER', 'BURGER'), ('LAVASH', 'LAVASH'), ('HAT DOG', 'HOT DOG'), ('PIZZA', 'PIZZA'), ('CHEESE BURGER', 'CHEESE BURGER')], max_length=255),
        ),
    ]
