# Generated by Django 4.2.1 on 2023-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_dastavka_location_alter_dastavka_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dastavka',
            name='all_price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
